export const SCAVENGE_REAGENTS = [
  { id: "boneDust", name: "Bone Dust", tier: 1 },
  { id: "slimeGel", name: "Slime Gel", tier: 1 },
  { id: "ashes", name: "Ashes", tier: 1 },
  { id: "limestoneDust", name: "Limestone Dust", tier: 1 },
  { id: "beastBlood", name: "Beast Blood", tier: 2 },
  { id: "insectIchor", name: "Insect Ichor", tier: 2 },
  { id: "ironShavings", name: "Iron Shavings", tier: 2 },
  { id: "saltCrystals", name: "Salt Crystals", tier: 2 },
  { id: "spiritResidue", name: "Spirit Residue", tier: 3 },
  { id: "pureSlime", name: "Pure Slime", tier: 3 },
  { id: "crystalDust", name: "Crystal Dust", tier: 3 },
  { id: "runicAsh", name: "Runic Ash", tier: 3 },
  { id: "ancientBlood", name: "Ancient Blood", tier: 4 },
  { id: "lifeEssence", name: "Life Essence", tier: 4 },
  { id: "runeFragment", name: "Rune Fragment", tier: 4 },
  { id: "ancientSap", name: "Ancient Sap", tier: 4 },
  { id: "vitalCore", name: "Vital Core", tier: 5 },
  { id: "alchemicalCore", name: "Alchemical Core", tier: 5 },
  { id: "philosophersAsh", name: "Philosopher's Ash", tier: 5 },
  { id: "worldseedFragment", name: "Worldseed Fragment", tier: 5 },
]

export const SCAVENGING_ZONES = [
  {
    id: "safe",
    name: "Safe Grounds",
    level: 1,
    xp: 10,
    reagents: SCAVENGE_REAGENTS.filter((r) => r.tier === 1),
    rolls: 1,
  },
  {
    id: "hostile",
    name: "Hostile Wilds",
    level: 21,
    xp: 20,
    reagents: SCAVENGE_REAGENTS.filter((r) => r.tier === 2),
    rolls: 1,
  },
  {
    id: "dangerous",
    name: "Dangerous Ruins",
    level: 41,
    xp: 34,
    reagents: SCAVENGE_REAGENTS.filter((r) => r.tier === 3),
    rolls: 2,
  },
  {
    id: "extreme",
    name: "Extreme Depths",
    level: 61,
    xp: 50,
    reagents: SCAVENGE_REAGENTS.filter((r) => r.tier === 4),
    rolls: 2,
  },
  {
    id: "forbidden",
    name: "Forbidden Sanctum",
    level: 81,
    xp: 70,
    reagents: SCAVENGE_REAGENTS.filter((r) => r.tier === 5),
    rolls: 3,
  },
]
